# Generated by Django 5.0 on 2024-01-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cfo', models.BigIntegerField()),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'dentistas',
            },
        ),
    ]
